server:
  http_listen_port: 9080

positions:
  filename: /tmp/positions.yaml

clients:
  # replace "loki" with server address for external hosts
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
    - targets:
      - localhost
      labels:
        job: varlogs
        __path__: /var/log/*log
