groups:
- name: targets
  rules:
  - alert: monitor_service_down
    expr: up == 0
    for: 30s
    labels:
      severity: critical
    annotations:
      summary: "Monitor service non-operational"
      description: "Service {{ $labels.instance }} is down."

- name: host
  rules:
  - alert: high_cpu_load
    expr: 100 - 100 * (avg(irate(node_cpu_seconds_total{mode="idle"}[30s]))) > 90
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Server under high load"
      description: 'CPU usage is {{ $value | printf "%.2f" }}%.'

  - alert: high_memory_load
    expr: (sum(node_memory_MemTotal_bytes) - sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) ) / sum(node_memory_MemTotal_bytes) * 100 > 85
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Server memory is almost full"
      description: 'Memory usage is {{ $value | printf "%.2f" }}%.'

  - alert: high_storage_load
    expr: (node_filesystem_size_bytes{fstype="aufs"} - node_filesystem_free_bytes{fstype="aufs"}) / node_filesystem_size_bytes{fstype="aufs"}  * 100 > 85
    for: 30s
    labels:
      severity: warning
    annotations:
      summary: "Server storage is almost full"
      description: 'Storage usage is {{ $value | printf "%.2f" }}%.'
    
- name: redis
  rules:
  - alert: redis_down
    expr: redis_up < 1
    labels:
      severity: page
    annotations:
      summary: Redis is down
